### ISSUE TITLE
how can i increase speed of animation /progress bar?

### ISSUE THREAD

**Issue by erumhannan** [lzyzsd/CircleProgress#10]
i m getting error in this line 

custom:circle_progress="25"
            custom:circle_finished_color="#ff0000"
            custom:circle_unfinished_color="#00ff00"
            custom:circle_text_color="#000000"
            custom:circle_suffix_text="$"
            custom:circle_text_size="16sp"

Multiple annotations found at this line:
	- error: No resource identifier found for attribute 'circle_text_size' in package 'com.example.batterylevel'
	- error: No resource identifier found for attribute 'circle_suffix_text' in package 
	 'com.example.batterylevel'
	- error: No resource identifier found for attribute 'circle_finished_color' in package 
	 'com.example.batterylevel'
	- error: No resource identifier found for attribute 'circle_progress' in package 'com.example.batterylevel'
	- error: No resource identifier found for attribute 'circle_unfinished_color' in package 
	 'com.example.batterylevel'
	- error: No resource identifier found for attribute 'circle_text_color' in package 'com.example.batterylevel'

**Comment by lzyzsd** [comment]
do you add this line in you layout?
xmlns:custom="http://schemas.android.com/apk/res-auto"
