### ISSUE TITLE
How to set Progress percentage value in Integer?

### ISSUE THREAD

**Issue by rranjithkumar100** [lzyzsd/CircleProgress#118]
In default percentage value show in float ex: 10.0%

I want show percentage in integer value like 10% 

How to achieve this ?

**Comment by rranjithkumar100** [comment]
Issue fixed by using old dependency 


    compile 'com.github.lzyzsd:circleprogress:1.1.0'

**Comment by weihongbo1** [comment]
the progress is showed by float  in new version, but you can't change the type
