### ISSUE TITLE
(CircleProgress) Last view "saved" ? Getting the same % for all views

### ISSUE THREAD

**Issue by SwiTool** [lzyzsd/CircleProgress#12]
Hi,

I'm saving my data in a database and when I load the fragment for a first time, it does a great job :
![First load](http://puu.sh/fcyCJ/da8cc040ad.png)
And then, at the second and furthers loads : it displays only 83%.
![Second load](http://puu.sh/fczg5/bae5a534d2.png)

When I debug here it displays me the good %. But in the View, i see only 83% as you saw before.
![Debug](http://puu.sh/fcz5L/db22422c77.png)

Any ideas if it is a bug ?

**Comment by maadani** [comment]
It could be a bug in your adapter.
Can you post your getView?

**Comment by SwiTool** [comment]
Sorry I don't have the code anymore... closed.
