### ISSUE TITLE
DonutProgress draw arc wrongly.

### ISSUE THREAD

**Issue by taoliuh** [lzyzsd/CircleProgress#14]
![screenshot_2015-02-27-13-57-24](https://cloud.githubusercontent.com/assets/3491083/6408129/eb5cd42e-be88-11e4-8b7d-77800af04cc0.png)
As the image above , 
```
     if (finishedStrokeWidth > unfinishedStrokeWidth) {
            finishedOuterRect.set(finishedStrokeWidth / 2,
                finishedStrokeWidth / 2,
                getWidth() - finishedStrokeWidth / 2,
                getHeight() - finishedStrokeWidth / 2);
            float delta = (finishedStrokeWidth - unfinishedStrokeWidth) / 2f;
            unfinishedOuterRect.set(unfinishedStrokeWidth / 2,
                unfinishedStrokeWidth / 2,
                getWidth() - unfinishedStrokeWidth / 2 - delta,
                getHeight() - unfinishedStrokeWidth / 2 - delta);
        } else {
            float delta = (unfinishedStrokeWidth - finishedStrokeWidth) / 2f;
            finishedOuterRect.set(finishedStrokeWidth / 2,
                finishedStrokeWidth / 2,
                getWidth() - finishedStrokeWidth / 2 - delta,
                getHeight() - finishedStrokeWidth / 2 - delta);
            unfinishedOuterRect.set(unfinishedStrokeWidth / 2,
                unfinishedStrokeWidth / 2,
                getWidth() - unfinishedStrokeWidth / 2,
                getHeight() - unfinishedStrokeWidth / 2);
        }

I modified so it would like this:
```
        float delta = Math.max(finishedStrokeWidth, unfinishedStrokeWidth);
        finishedOuterRect.set(delta,
                delta,
                getWidth() - delta,
                getHeight() - delta);
        unfinishedOuterRect.set(delta,
                delta,
                getWidth() - delta,
                getHeight() - delta);
![screenshot_2015-02-27-14-06-14](https://cloud.githubusercontent.com/assets/3491083/6408182/2941fb10-be8a-11e4-9051-9302be8c7d1e.png)

the problem resolved, and I commited a PR.

**Comment by lzyzsd** [comment]
thanks, but I did not receive your PR, do you forget it?

**Comment by taoliuh** [comment]
Yeah, I pushed just now.
