### ISSUE TITLE
Animation on ArcProgress

### ISSUE THREAD

**Issue by samsoft00** [lzyzsd/CircleProgress#17]
Please help me, how can i Animate ArcProgress?? i'll appreciate if you can explain with detailed discription

**Comment by lzyzsd** [comment]
see the example module, just use setProgress

**Comment by samsoft00** [comment]
Try out your suggestion but its not working, maybe you don't have a full understanding of what i'm saying...  when user get to the activity, i want the ArcProgress animate from 0% to whatever percentage assign in the code. that's just the simple behavior i want to implement, is this possible? if yes... how>?

**Comment by lzyzsd** [comment]
you can just start a timer or thread to update progress value, this lib does not provide animation feature.
