### ISSUE TITLE
Float Value Support 

### ISSUE THREAD

**Issue by shivasurya** [lzyzsd/CircleProgress#20]
This library is excellent ! 
pls support for float values for progress! 
however cast can be used! but i need to show values in float!

thanks in advance!

**Comment by hoseinit** [comment]
I am really in need of float value support, too. 
I do cast it to show integer but I can't show float numbers inside the arcprogress

**Comment by hoseinit** [comment]
@shivasurya I have managed it to support floats in #87

**Comment by shivasurya** [comment]
Sure will check it out! Thanks

**Comment by KhaledLela** [comment]
@shivasurya @hoseinit 
Please checkout my PR for handling this progress floating point without change library
#103 
```
        <attr name="donut_digits" format="integer"/>
        setProgressFloating(int digits) 
```
digits= 0 > int value.
digits= 1 > 70.5
digits=2 > 65.45
,..etc

**Comment by shivasurya** [comment]
sure will check out 👍

**Comment by ahmadarslan13** [comment]
This library is awesome seriously.
I have a question related to the decimal value, Can we remove it from the progress?

Right now I am setting progress like
circleProgressView.setProgress((int) percentage);
