### ISSUE TITLE
ArcAngle property is not working

### ISSUE THREAD

**Issue by vivekm26** [lzyzsd/CircleProgress#24]
When ever I set the arc angle property in xml file and run the app it fails with 
android.view.InflateException: Binary XML file line #128: Error inflating class com.github.lzyzsd.circleprogress.ArcProgress

**Comment by technohowl** [comment]
I am getting the same exception on setting arc_angle. An example of how to set it would help.

**Comment by bhaidaya** [comment]
Same issue. Any support appreciated.

**Comment by lzyzsd** [comment]
@bhaidaya I will check this, thx

**Comment by bhaidaya** [comment]
Thanks! FYI i used the Gradle version first. When i pulled the raw version from here it worked, however i had lost control of setting the background color of the widget until i added that styleable.

**Comment by lzyzsd** [comment]
@bhaidaya Please use jitpack.io ， its more convenient

**Comment by KhaledLela** [comment]
I got the same issue when set arch angle property

**Comment by avp2306** [comment]
Confirmed here as well. 

I tried setting inline in XML as well as defining a value dimen resources both result in the error described in this tread.

**Comment by lzyzsd** [comment]
please use the latest version from jitpack.io, since I do not upload new version to jcenter or maven center .
jitpack is much more convenient.
