### ISSUE TITLE
Donut Progress start at 12 o'clock

### ISSUE THREAD

**Issue by omatt** [lzyzsd/CircleProgress#30]
Is there any way to set the progress donut to start at 12 o'clock(90°) instead of 3 o'clock(0°)?

**Comment by nagendraksrivastava** [comment]
I am also looking for the same feature

**Comment by omatt** [comment]
I just set the color of the progress text into transparent and rotated the DonutProgress view. It's just a workaround and not a pretty implementation.

**Comment by X4mp** [comment]
I would need the same feature. Is there any chance that you can add a property to set the start of the progress to 12 o'clock(90°)?

**Comment by omatt** [comment]
```xml
<com.github.lzyzsd.circleprogress.DonutProgress
...
android:rotation="270"
custom:donut_text_color="#00000000"/>
```
This is just a quick fix and not really a good solution. I set the text color to transparent since the text will also be rotated along with the DonutProgress.

**Comment by X4mp** [comment]
ok thx. Unfortunatelly I need the text, so rotation is not what I need. I created a Pull-Request for this issue. Please review pr #31 and give me some feedback on it.
