### ISSUE TITLE
start progress from top

### ISSUE THREAD

**Issue by lupajz** [lzyzsd/CircleProgress#32]
Would it be possible to have attribute wich will let us set starting angle of progress ? Like for values 0 or 360 the progress would start from top of the circle ?

**Comment by X4mp** [comment]
I proposed this feature within PR #31 
It just needs to be accepted. If you need this feature urgently you can check out my forked repository at 
https://github.com/X4mp/CircleProgress

**Comment by lupajz** [comment]
wow thanks :) so this marks it as resolved :+1:

**Comment by mikelittman** [comment]
It doesn't look like this is in the maven repository. Will this update be pushed any time soon?

**Comment by Palantir-NR** [comment]
you can just apply rotation to your progress in xml
