### ISSUE TITLE
How to add an animation for progress

### ISSUE THREAD

**Issue by Andecy** [lzyzsd/CircleProgress#48]
such as，current progress is 55%，when user open app，see the progress will start with 0% to 55% with a smoothy animation

**Comment by XxGoliathusxX** [comment]
Example:
DonutProgress donut = (DonutProgress) customView.findViewById(R.id.progress);  
ObjectAnimator animation = ObjectAnimator.ofInt(donut, "progress", 0, 55);
        animation.setDuration(55 * 25);//25 for a fast but not to fast animation
        animation.setInterpolator(new DecelerateInterpolator());
        animation.start();

**Comment by Andecy** [comment]
soga ObjectAnimator!
thank you!

**Comment by satheeshwaran** [comment]
@XxGoliathusxX You are simply great!! you could add this as a pull request.
