### ISSUE TITLE
Progress starting degree

### ISSUE THREAD

**Issue by cemtufekci** [lzyzsd/CircleProgress#5]
I would like to know if there is a way to start progress at 0 degree.

**Comment by akkisjoy** [comment]
use android:rotation="-90"

**Comment by gkcgautam** [comment]
@akkisjoy rotation works as temporary solution only if there is no text. Otherwise the text also gets rotated with the view.

**Comment by gkcgautam** [comment]
@lzyzsd any solution for this?

**Comment by lzyzsd** [comment]
@gkcgautam I will  add this feature in the next release
