### ISSUE TITLE
CircleProgress start angle

### ISSUE THREAD

**Issue by guyzk** [lzyzsd/CircleProgress#51]
Is it possible to modify the CircleProgress to start from the top instead of from a 90 degree angle

**Comment by DhavalsShah** [comment]
try android:rotation attribute. It works great in DonutProgress. So, I think it should also work with CirclProgress as well. 
Usage: android:rotation="rotation of the view, in degrees. " You can also use setRotation() method if you want to rotate programatically.
Try that. Hope this info helps.

**Comment by nish-d** [comment]
That rotates the text inside too. Is there some other solution?

**Comment by nish-d** [comment]
One way could be to set the progress as (100 - required progress). And change the finished_color and unfinished_color appropriately. For example, if you want to display 20%  progress, set the progress to 80% and swap the colors for finished and unfinished progress.

**Comment by DhavalsShah** [comment]
@nish-d, I agree it rotates the text inside too, But I have solved that one by putting an attribute of custom:circle_text_color="@android:color/transparent",that makes the default text to transparent(i.e that user can not see) and then I put my own textview inside the progressbar using the framelayout. so its override the default  rotated text, so user can see only the our textview which is inside the framelayout.
 <FrameLayout>
 <CircleProgress custom:circle_text_color="@android:color/transparent"></CircleProgress>
<TextView android:text="20%"></TextView>
</FrameLayout>

Hope this helps you.

**Comment by nish-d** [comment]
This is certainly an innovative solution. Also I just found out there is a method, setStartingDegree(), that does the same.

**Comment by amardeshbd** [comment]
@lzyzsd I see `attr: donut_circle_starting_degree` & `setStartingDegree(int startingDegree)` in [master-branch](https://github.com/lzyzsd/CircleProgress/blob/master/library/src/main/java/com/github/lzyzsd/circleprogress/DonutProgress.java#L154)

But this is not available in `1.1.0` release in [maven central rep](http://search.maven.org/#artifactdetails%7Ccom.github.lzyzsd%7Ccircleprogress%7C1.1.0%7Caar) is there any plan to publish new version with these changes & features?

**Comment by AdityaLabhade** [comment]
Here is my Solution :
 In XMl 

<RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center">

        <TextView
            android:id="@+id/tv_counter"
            android:text="0"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:textSize="12dp"
            android:textColor="#000"/>

        <com.github.lzyzsd.circleprogress.DonutProgress
            android:id="@+id/donut_progress"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:rotation="-90"
            android:layout_centerInParent="true"
            custom:donut_text_color="@android:color/transparent"
            custom:donut_max="15"
            custom:donut_progress="0"/>
    </RelativeLayout>

In Java

final DonutProgress  donutProgress = (DonutProgress) findViewById(R.id.donut_progress);
        final TextView tv_counter = (TextView) findViewById(R.id.tv_counter);

	int count;  //Need of global declaration

        final Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                count ++ ;
                if(count != 0)
                {
                    handler.postDelayed(this, 1000);
                }

                donutProgress.setProgress(count);
                tv_counter.setText(String.valueOf(count));
            }
        }, 1000);

**Comment by lzyzsd** [comment]
@amardeshbd please use jitpack.io， I havent update mvn center for a long time
