### ISSUE TITLE
Set color programatically ?

### ISSUE THREAD

**Issue by TcQPAD** [lzyzsd/CircleProgress#60]
Hello,

First of all thanks for this very nice and easy use library :-)

I'd like to know if it's possible to change the finished_color programatically. I'm having trouble doing it :

Using `donutProgress.setFinishedStrokeColor(R.color.orange);` or whatever color won't do anything, instead it puts a blue/purple color as you can see below :

![issue_donut_progress](https://cloud.githubusercontent.com/assets/17066590/17860215/f54017e4-688c-11e6-999e-70e34c314e19.png)

Am I using setFinishedStrokeColor the right way ?
Thanks in advance, Max

**Comment by TcQPAD** [comment]
I solved it by using : 

`donutProgress.setFinishedStrokeColor(Color.parseColor("#color_code"));`

It seems like the method can't manage to use resource colors such as R.color.mycolor.

**Comment by sajadmaster** [comment]
Thank you. I had the same issue
