### ISSUE TITLE
Build gradle should be like this compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'

### ISSUE THREAD

**Issue by tuanphambiglab** [lzyzsd/CircleProgress#69]
compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'

Hi, build gradle with compile 'com.github.lzyzsd:circleprogress:1.1.0' doesn't work( i mean in guidance document)
should be like compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'

Thanks

**Comment by jiawenzhang** [comment]
should we use 1.1.1 or 1.2.0 or 1.1.0? it is confusing

**Comment by lekeCoder** [comment]
@jiawenzhang l used 1.2.0 and it worked
