### ISSUE TITLE
Gradle dependencies not found

### ISSUE THREAD

**Issue by taojunpo** [lzyzsd/CircleProgress#76]
In the README.md the gradle dependencies is `compile 'com.github.lzyzsd:circleprogress:1.1.1'`, but it doesn't work, I change it to `compile 'com.github.lzyzsd:CircleProgress:v1.2.0'`, then it works. Please change this in the README.md file. Thanks for your contribution!

**Comment by tuytuy** [comment]
I have tried with compile 'com.github.lzyzsd:CircleProgress:v1.2.0' but it is still not working :/

**Comment by rahmadsetiawan** [comment]
Thanks bro!

**Comment by yhaznedar** [comment]
thanks mate!

**Comment by odyodyodys** [comment]
# solution
Replace `compile 'com.github.lzyzsd:circleprogress:1.1.1'`
with `compile 'com.github.lzyzsd:circleprogress:v1.1.1'`.

This is because `jitpack.io` wants tag as the last parameter and @lzyzsd's tag is `v1.1.1` not `1.1.1`.

**Comment by lzyzsd** [comment]
please use jitpack.io, thanks @odyodyodys I have changed the latese tag to 1.2.1, no v prefix now
