### ISSUE TITLE
how can i resize "percent"-Icon of ArcProgress?

### ISSUE THREAD

**Issue by talalong** [lzyzsd/CircleProgress#81]
Textsize can be ajusted, but not percent icon in ArcProgress.
Please help!

**Comment by azizoglu** [comment]
You can update **_default_suffix_text_size = Utils.sp2px(getResources(), 15);_** in **_ArcProgress.java_**. Update value 15 what you want.

**Comment by talalong** [comment]
thanks for your answer, but ArcProgress.java is locked. so im not able to edit it. :(

**Comment by azizoglu** [comment]
Copy code in _ArcProgress.java_ and create your own java class named _ArcProgress.java_. Then you can use your class for ArcProgress.

**Comment by talalong** [comment]
Ah Okay. Thanks
